notifications:
  slack: wsi-t113:SRHSOd3CgFDUwFxqv8SCXuIf
  email: false

sudo: false

language: ruby

services:
 - docker

script:
 - echo 'Build and check docker image'
 - docker build -t denovogear .
 - docker images | grep -c denovogear
 - echo 'Verify program(s) from this repo'
 - docker run -t --rm denovogear denovogear -h


